#!/usr/bin/env bash
# configure Nginx's HTTP response contains
# custom header (web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
new_config="server_name _; \n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"
sudo sed -i "s/server_name _;/$new_config/" /etc/nginx/sites-enabled/default

sudo service nginx restart
